version: "3"

services:
  db:
    container_name: "postgres"
    image: postgres:11
    environment:
        DB_HOST: "localhost"
        POSTGRES_DB: "tccApi"
        POSTGRES_USER: "postgres"
        POSTGRES_PASSWORD: "docker"
    ports:
        - "5432:5432"
    restart: "always"
  mongodb:
    container_name: "mongodb"
    image: mongo
    environment:
        DB_HOST: "localhost"
    ports:
        - "27017:27017"
    restart: "always"
  app:
    build: .
    ports:
        - 3333:3333
        - 9229:9229
    image: app
    command: >
      sh -c "npx sequelize db:migrate &&
             yarn dev:debug"
    volumes:
        - .:/usr/app
    environment:
        NODE_ENV: development
        DB_HOST: db
        DB_USER: postgres
        DB_PASS: docker
        DB_NAME: tccApi
        DB_MONGO: mongodb
        SECRET_JWT: e372985389e031db533d2fb315d666f0
        EXPIRES_JWT: 99d
        JWT_USER: alexa_unisanta@unisanta.br
        JWT_PASSWORD: alexatcc_apiturmaTI@345
    depends_on:
        - db
        - mongodb
